######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 18 10:50:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QuantServerUI.h \
           ../Include/NQTV.h \
           ../Include/Settings.h \
           ../Include/Includes.h \
           ../Include/ItchIncludes.h
SOURCES += main.cpp QuantServerUI.cpp
