######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 19 16:41:02 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QuantServer.h ../Include/Settings.h ../Include/Includes.h
SOURCES += main.cpp QuantServer.cpp
