######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 19 14:11:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QuantServerUI.h ../Include/Settings.h ../Include/Includes.h
SOURCES += main.cpp QuantServerUI.cpp
